version: '2'

services:
    # PostgreSQL database
    db:
        image: postgres:9.6
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"

    # Redis
    redis:
        image: redis:3.2.7
        hostname: redis

  # RabbitMQ
    rabbit:
        hostname: rabbit
        image: rabbitmq:3.6.6
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"  # we forward this port because it's useful for debugging
            - "15672:15672"  # here, we can access rabbitmq management plugin

    # Django web server
    web:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: ./run_web.sh
        volumes:
            - .:/srv/www/memex/memex  # mount current directory inside container
        ports:
            - "8000:8000"
        # set up links so that web knows about db, rabbit and redis
        links:
            - db
            - rabbit
            - redis
        depends_on:
            - db

    # Celery worker
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_celery.sh
        volumes:
            - .:/srv/www/memex/memex
        links:
            - db
            - rabbit
            - redis
        depends_on:
            - rabbit


    # # Flower
    # flower:
    #     image: totem/celery-flower-docker
    #     hostname: flower
    #     environment:
    #       - AMQP_USERNAME=admin
    #       - AMQP_PASSWORD=mypass
    #       - AMQP_HOST=rabbit
    #       - AMQP_PORT=5672
    #       - AMQP_ADMIN_USERNAME=admin
    #       - AMQP_ADMIN_PASSWORD=mypass
    #       - AMQP_ADMIN_HOST=rabbit
    #       - AMQP_ADMIN_PORT=15672
    #
    #     links:
    #       - rabbit
    #       - worker
    #     depends_on:
    #       - worker
    #     ports:
    #       - "5555:5555"
