# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memes', '0013_auto_20170322_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeDataSnapshot24Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('crs_l24hrs', models.IntegerField()),
                ('np_l24hrs', models.IntegerField()),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Meme')),
            ],
            options={
                'verbose_name': 'Meme data snapshot 24 hour',
            },
        ),
        migrations.CreateModel(
            name='MemeDataSnapshot30Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('crs_l30days', models.IntegerField()),
                ('np_l30days', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Meme')),
            ],
            options={
                'verbose_name': 'Meme data snapshot 30 days',
            },
        ),
        migrations.CreateModel(
            name='MemeDataSnapshot7Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('crs_l7days', models.IntegerField()),
                ('np_l7days', models.IntegerField()),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Meme')),
            ],
            options={
                'verbose_name': 'Meme data snapshot 7 days',
            },
        ),
    ]
