# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memedatasnapshot24hour',
            name='crs_l24hrs_change',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
