# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=200)),
                ('likely_meme', models.CharField(max_length=200)),
                ('image_similarity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('image_url', models.URLField()),
                ('gilded', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('title', models.CharField(max_length=400)),
                ('subreddit', models.CharField(max_length=200)),
                ('subreddit_id', models.CharField(max_length=200)),
                ('permalink', models.URLField()),
                ('submission_created', models.DateTimeField()),
                ('date_crawled', models.DateTimeField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
