# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0011_auto_20170225_0440'),
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPostSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crawled', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('gilded', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='redditpost',
            options={'ordering': ('submission_created',), 'verbose_name': 'Reddit Post'},
        ),
        migrations.RemoveField(
            model_name='redditpost',
            name='date_crawled',
        ),
        migrations.RemoveField(
            model_name='redditpost',
            name='gilded',
        ),
        migrations.RemoveField(
            model_name='redditpost',
            name='score',
        ),
        migrations.AddField(
            model_name='redditpost',
            name='closest_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memes.MemeFile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='likely_meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Meme'),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='permalink',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='submission_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='redditpostsnapshot',
            name='reddit_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_post_snapshots', to='reddit.RedditPost'),
        ),
    ]
