# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20170214_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPostSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crawled', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('gilded', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='redditpost',
            name='date_crawled',
        ),
        migrations.RemoveField(
            model_name='redditpost',
            name='gilded',
        ),
        migrations.RemoveField(
            model_name='redditpost',
            name='score',
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='submission_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='redditpostsnapshot',
            name='reddit_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.RedditPost'),
        ),
    ]
