# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20170225_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redditpostsnapshot',
            name='num_comments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditpostsnapshot',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
