# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20170225_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditpost',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='redditpostsnapshot',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditpostsnapshot',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
