# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0011_auto_20170225_0039'),
        ('reddit', '0004_auto_20170221_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditpost',
            name='likely_meme',
        ),
        migrations.AddField(
            model_name='redditpost',
            name='closest_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memes.Meme'),
            preserve_default=False,
        ),
    ]
