# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0011_auto_20170225_0039'),
        ('reddit', '0005_auto_20170225_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redditpost',
            options={'ordering': ('submission_created',), 'verbose_name': 'Reddit Post'},
        ),
        migrations.AddField(
            model_name='redditpost',
            name='likely_meme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memes.Meme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='closest_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.MemeFile'),
        ),
    ]
