# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0006_auto_20170225_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='image_url',
            field=models.URLField(),
        ),
    ]
