# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0008_auto_20170225_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='submission_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='submission_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_id',
            field=models.CharField(max_length=100),
        ),
    ]
