# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0010_auto_20170225_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpostsnapshot',
            name='score',
            field=models.IntegerField(),
        ),
    ]
