# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_auto_20170213_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='likely_meme',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='submission_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit',
            field=models.CharField(max_length=200),
        ),
    ]
