# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20170213_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Get Latest 30 Advice Animals', 'get_latest_30_advice_animals')], max_length=100),
        ),
    ]
