# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_delete_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedditPost',
        ),
    ]
