# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0009_delete_redditpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Meme')),
            ],
        ),
    ]
