# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0010_memefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ('name',), 'verbose_name': 'Meme'},
        ),
        migrations.AlterModelOptions(
            name='memefile',
            options={'verbose_name': 'Meme Filename'},
        ),
    ]
