# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0011_auto_20170225_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='memefile',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
